site_name: "Hopsworks Documentation"
site_description: "Official documentation for Hopsworks and its Feature Store - an open source data-intensive AI platform used for the development and operation of machine learning models at scale."
site_author: "Logical Clocks"
site_url: "https://docs.hopsworks.ai/"

# Repository
repo_name: logicalclocks/hopsworks
repo_url: https://github.com/logicalclocks/hopsworks
edit_uri: ""

nav:
  - üè† Home: index.md
  - Getting Started:
    - Feature Store:
      - Quickstart: getting_started/fs/index.md
      - Tutorials:
        - AML Tutorial: getting_started/fs/tutorials/aml.md
  - Concepts:
    - Hopsworks Platform: concepts/hopsworks.md
    - Feature Store:
      - Architecture: concepts/fs/index.md #hsfs
      - Feature Groups:
        - Overview: concepts/fs/feature_group/fg_overview.md
        - Write APIs: concepts/fs/feature_group/write_apis.md
        - Feature Pipelines: concepts/fs/feature_group/feature_pipelines.md
        - External Feature Groups: concepts/fs/feature_group/external_fg.md
        - Feature Validation/Statistics: concepts/fs/feature_group/fg_statistics.md
        - Versioning: concepts/fs/feature_group/versioning.md
      - Feature Views:
        - Overview: concepts/fs/feature_view/fv_overview.md
        - Training Data: concepts/fs/feature_view/training_data.md 
        - Consistent Transformations: concepts/fs/feature_view/transformations.md
        - Online API: concepts/fs/feature_view/online_api.md
        - Statistics: concepts/fs/feature_view/statistics.md
        - Versioning: concepts/fs/feature_view/versioning.md
    - Projects:
        - Governance: concepts/projects/governance.md
        - Data Storage/Sharing: concepts/projects/storage.md 
        - CI/CD: concepts/projects/cicd.md
    - MLOps:
      - MLOps Flywheel: concepts/mlops/flywheel.md
      - Model Registry: concepts/mlops/registry.md
      - Model Serving: concepts/mlops/kserve.md # create, read, version
      - Vector Database: concepts/mlops/opensearch.md 
    - Development:
        - Outside Hopsworks: concepts/dev/outside.md # api-keys
        - Inside Hopsworks: concepts/dev/inside.md
  - Guides:
    - user_guides/index.md
    - Feature Store:
      - user_guides/fs/index.md
      - Storage Connector:
        - user_guides/fs/storage_connector/index.md
        - Configuration and Creation:
          - JDBC: user_guides/fs/storage_connector/creation/jdbc.md
          - Snowflake: user_guides/fs/storage_connector/creation/snowflake.md
          - Kafka: user_guides/fs/storage_connector/creation/kafka.md 
          - HopsFS: user_guides/fs/storage_connector/creation/hopsfs.md
          - S3: user_guides/fs/storage_connector/creation/s3.md
          - Redshift: user_guides/fs/storage_connector/creation/redshift.md
          - ADLS: user_guides/fs/storage_connector/creation/adls.md
          - BigQuery: user_guides/fs/storage_connector/creation/bigquery.md
          - GCS: user_guides/fs/storage_connector/creation/gcs.md
        - Usage: user_guides/fs/storage_connector/usage.md
      - Feature Group:
        - user_guides/fs/feature_group/index.md
        - Create: user_guides/fs/feature_group/create.md
        - Create External: user_guides/fs/feature_group/create_external.md
        - Data Types and Schema management: user_guides/fs/feature_group/data_types.md
        - Statistics: user_guides/fs/feature_group/statistics.md
      - Feature View:
        - user_guides/fs/feature_view/index.md
        - Overview: user_guides/fs/dummy.md
        - Query: user_guides/fs/dummy.md
        - Batch data: user_guides/fs/dummy.md
        - Online vectors: user_guides/fs/dummy.md
        - Training data: user_guides/fs/dummy.md
        - Transformation Functions: user_guides/fs/dummy.md
      - Tags and Keywords: user_guides/fs/dummy.md
    - MLOps:
      - user_guides/ml/index.md
      - Model Registry:
        - user_guides/ml/model/index.md
        - Frameworks:
          - TensorFlow: user_guides/ml/model/frameworks/tf.md
          - Scikit-Learn: user_guides/ml/model/frameworks/skl.md
          - PyTorch: user_guides/ml/model/frameworks/torch.md
          - Python: user_guides/ml/model/frameworks/torch.md
        - Model Schema: user_guides/ml/model/schema.md
        - Input Example: user_guides/ml/model/input.md
      - Model Serving:
        - user_guides/ml/deployment/index.md
        - Frameworks:
            - TensorFlow: user_guides/ml/model/frameworks/tf.md
            - Scikit-Learn: user_guides/ml/model/frameworks/skl.md
            - PyTorch: user_guides/ml/model/frameworks/torch.md
            - Python: user_guides/ml/model/frameworks/torch.md
        - Predictor: user_guides/ml/deployment/predictor.md
        - Transformer: user_guides/ml/deployment/transformer.md
        - Resource Configuration: user_guides/ml/deployment/resources.md
        - Inference Logger: user_guides/ml/deployment/inference-logger.md
        - Inference Batcher: user_guides/ml/deployment/inference-batcher.md
      - Vector Database: user_guides/ml/vector_database/vector_database.md
    - Integrations:
      - Python: integrations/dummy.md
      - Databricks: integrations/dummy.md
      - AWS Sagemaker: integrations/dummy.md
      - AWS EMR: integrations/dummy.md
      - Azure HDInsight: integrations/dummy.md
      - Azure Machine Learning: integrations/dummy.md
      - Apache Spark: integrations/dummy.md
    - Projects:
      - Authentication: user_guides/projects/dummy.md
      - Projects:
          - Create Project: user_guides/projects/project/create_project.md
          - Add Members: user_guides/projects/project/add_members.md
      - Python:
          - Install library:
              - Git source: user_guides/projects/python/python_install.md
              - pip: user_guides/projects/python/python_install.md
              - conda: user_guides/projects/python/python_install.md
              - distribution: user_guides/projects/python/python_install.md

          - Export environment: user_guides/projects/python/python_env_export.md
          - Recreate environment: user_guides/projects/python/python_env_recreate.md
      - Jupyter:
          - Run Spark Notebook: user_guides/projects/jupyter/spark_notebook.md
          - Run Python Notebook: user_guides/projects/jupyter/python_notebook.md
      - Jobs:
          - Run PySpark Job: user_guides/projects/jobs/pyspark_job.md
          - Run Spark Job: user_guides/projects/jobs/spark_job.md
          - Run Python Job: user_guides/projects/jobs/python_job.md
          - Alerts: user_guides/projects/jobs/alert.md
      - OpenSearch:
          - Connect: user_guides/projects/opensearch/connect.md
          - Vector Database: user_guides/projects/opensearch/vector_database.md
      - Airflow: user_guides/projects/dummy.md
      - Kafka:
          - Create Schema: user_guides/projects/kafka/create_schema.md
          - Create Topic: user_guides/projects/kafka/create_topic.md
          - Produce messages: user_guides/projects/kafka/produce_messages.md
          - Consume messages: user_guides/projects/kafka/consume_messages.md
      - Git:
          - Configure Git Provider: user_guides/projects/git/configure_git_provider.md
          - Clone Repository: user_guides/projects/git/clone_repo.md
      - Secrets:
          - Create Secret: user_guides/projects/secrets/create_secret.md
      - Api Keys:
          - Create API Key: user_guides/projects/api_key/create_api_key.md
      - AWS IAM Roles: user_guides/projects/iam_role/iam_role_chaining.md
      - Search: user_guides/projects/dummy.md
      - Hops File System (HopsFS): user_guides/projects/dummy.md
  - Setup and Installation:
      - AWS:
          - Getting Started: setup_installation/aws/getting_started.md
          - Cluster Creation: setup_installation/aws/cluster_creation.md
          - EKS/ECR integration: setup_installation/aws/eks_ecr_integration.md
          - Limiting Permissions: setup_installation/aws/restrictive_permissions.md
          - Cluster upgrade: 
            - Version 2.4 or newer: setup_installation/aws/upgrade_2.4.md
            - Version 2.2 or older: setup_installation/aws/upgrade.md
      - Azure:
          - Getting Started: setup_installation/azure/getting_started.md
          - Cluster Creation: setup_installation/azure/cluster_creation.md
          - AKS/ACR integration: setup_installation/azure/aks_acr_integration.md
          - Limiting Permissions: setup_installation/azure/restrictive_permissions.md
          - Cluster upgrade: 
            - Version 2.4 or newer: setup_installation/azure/upgrade_2.4.md
            - Version 2.2 or older: setup_installation/azure/upgrade.md
      - GCP:
          - Getting Started: setup_installation/gcp/getting_started.md
          - Cluster Creation: setup_installation/gcp/cluster_creation.md
          - Limiting Permissions: setup_installation/gcp/restrictive_permissions.md
      - Common:
          - Services: setup_installation/common/services.md
          - Adding and Removing workers: setup_installation/common/adding_removing_workers.md
          - Autoscaling: setup_installation/common/autoscaling.md
          - Scaling up: setup_installation/common/scalingup.md
          - GPU support: setup_installation/common/gpu_support.md
          - User management: setup_installation/common/user_management.md
          - Managed RonDB: setup_installation/common/rondb.md
          - Single Sign On:
              - Hopsworks:
                  - OAuth2: setup_installation/common/sso/oauth.md
                  - LDAP: setup_installation/common/sso/ldap.md
              - Hopsworks.ai: setup_installation/common/sso/sso.md
          - API Key: setup_installation/common/api_key.md
          - Terraform: setup_installation/common/terraform.md
      - On-Prem:
          - Hopsworks Installer: setup_installation/on_prem/hopsworks_installer.md
  - Administration:
      - Introduction: admin/index.md
      - Authentication:
          - Configure Authentication: admin/auth.md
          - Configure OAuth2:
              - Register an Identity Provider: admin/oauth2/create-client.md
              - Create Okta Client: admin/oauth2/create-okta-client.md
              - Create Azure Client: admin/oauth2/create-azure-client.md
          - Configure LDAP/Kerberos:
              - Configure LDAP: admin/ldap/configure-ldap.md
              - Configure Kerberos: admin/ldap/configure-krb.md
              - Configure server for LDAP and Kerberos: admin/ldap/configure-server.md
      - Project management: administration/dummy.md
      - User Management: admin/user.md
      - Configure Alerts: admin/alert.md
      - Manage Services: admin/services.md
      - Tags: administration/dummy.md
      - Monitoring: administration/dummy.md
      - IAM Role Chaining: admin/roleChaining.md 
  - API: reference_guides/index.md
  - Community: https://community.hopsworks.ai/

theme:
  name: material
  favicon: assets/images/favicon.ico
  logo: assets/images/hops-logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: "Roboto"
    code: "IBM Plex Mono"
  palette:
    accent: teal
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hopsworks
    - icon: fontawesome/brands/github
      link: https://github.com/logicalclocks/hopsworks
    - icon: fontawesome/brands/discourse
      link: https://community.hopsworks.ai/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/hopsworks/
  analytics:
    provider: google
    # switch for new token
    property: UA-85730257-4

extra_css:
    - css/custom.css
    - css/marctech.css

plugins:
    - search

markdown_extensions:
    - admonition
    - codehilite
    - footnotes
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.arithmatex
    - pymdownx.superfences
    - pymdownx.details
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.critic
    - attr_list
    - md_in_html
    - toc:
        permalink: "#"
    - pymdownx.tasklist:
        custom_checkbox: true
    - markdown_include.include:
        base_path: docs
